// Mocks generated by Mockito 5.4.6 from annotations
// in cashup/test/presentation/blocs/auth/auth_bloc_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:cashup/domain/entities/user_entity.dart' as _i2;
import 'package:cashup/domain/repositories/auth_repository.dart' as _i9;
import 'package:cashup/domain/usecases/auth/get_current_user.dart' as _i7;
import 'package:cashup/domain/usecases/auth/login_user.dart' as _i5;
import 'package:cashup/domain/usecases/auth/logout_user.dart' as _i6;
import 'package:cashup/domain/usecases/auth/register_user.dart' as _i3;
import 'package:cashup/domain/usecases/auth/reset_password.dart' as _i8;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeUserEntity_0 extends _i1.SmartFake implements _i2.UserEntity {
  _FakeUserEntity_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [RegisterUser].
///
/// See the documentation for Mockito's code generation for more information.
class MockRegisterUser extends _i1.Mock implements _i3.RegisterUser {
  MockRegisterUser() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.UserEntity> call({
    required String? email,
    required String? password,
    required String? firstName,
    required String? lastName,
    required DateTime? birthDate,
    String? gender,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#call, [], {
              #email: email,
              #password: password,
              #firstName: firstName,
              #lastName: lastName,
              #birthDate: birthDate,
              #gender: gender,
            }),
            returnValue: _i4.Future<_i2.UserEntity>.value(
              _FakeUserEntity_0(
                this,
                Invocation.method(#call, [], {
                  #email: email,
                  #password: password,
                  #firstName: firstName,
                  #lastName: lastName,
                  #birthDate: birthDate,
                  #gender: gender,
                }),
              ),
            ),
          )
          as _i4.Future<_i2.UserEntity>);
}

/// A class which mocks [LoginUser].
///
/// See the documentation for Mockito's code generation for more information.
class MockLoginUser extends _i1.Mock implements _i5.LoginUser {
  MockLoginUser() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.UserEntity> call({
    required String? email,
    required String? password,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#call, [], {#email: email, #password: password}),
            returnValue: _i4.Future<_i2.UserEntity>.value(
              _FakeUserEntity_0(
                this,
                Invocation.method(#call, [], {
                  #email: email,
                  #password: password,
                }),
              ),
            ),
          )
          as _i4.Future<_i2.UserEntity>);
}

/// A class which mocks [LogoutUser].
///
/// See the documentation for Mockito's code generation for more information.
class MockLogoutUser extends _i1.Mock implements _i6.LogoutUser {
  MockLogoutUser() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<void> call() =>
      (super.noSuchMethod(
            Invocation.method(#call, []),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);
}

/// A class which mocks [GetCurrentUser].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetCurrentUser extends _i1.Mock implements _i7.GetCurrentUser {
  MockGetCurrentUser() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.UserEntity?> call() =>
      (super.noSuchMethod(
            Invocation.method(#call, []),
            returnValue: _i4.Future<_i2.UserEntity?>.value(),
          )
          as _i4.Future<_i2.UserEntity?>);
}

/// A class which mocks [ResetPassword].
///
/// See the documentation for Mockito's code generation for more information.
class MockResetPassword extends _i1.Mock implements _i8.ResetPassword {
  MockResetPassword() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<void> call({required String? email}) =>
      (super.noSuchMethod(
            Invocation.method(#call, [], {#email: email}),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);
}

/// A class which mocks [AuthRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockAuthRepository extends _i1.Mock implements _i9.AuthRepository {
  MockAuthRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Stream<_i2.UserEntity?> get authStateChanges =>
      (super.noSuchMethod(
            Invocation.getter(#authStateChanges),
            returnValue: _i4.Stream<_i2.UserEntity?>.empty(),
          )
          as _i4.Stream<_i2.UserEntity?>);

  @override
  _i4.Future<_i2.UserEntity> register({
    required String? email,
    required String? password,
    required String? firstName,
    required String? lastName,
    required DateTime? birthDate,
    String? gender,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#register, [], {
              #email: email,
              #password: password,
              #firstName: firstName,
              #lastName: lastName,
              #birthDate: birthDate,
              #gender: gender,
            }),
            returnValue: _i4.Future<_i2.UserEntity>.value(
              _FakeUserEntity_0(
                this,
                Invocation.method(#register, [], {
                  #email: email,
                  #password: password,
                  #firstName: firstName,
                  #lastName: lastName,
                  #birthDate: birthDate,
                  #gender: gender,
                }),
              ),
            ),
          )
          as _i4.Future<_i2.UserEntity>);

  @override
  _i4.Future<_i2.UserEntity> login({
    required String? email,
    required String? password,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#login, [], {#email: email, #password: password}),
            returnValue: _i4.Future<_i2.UserEntity>.value(
              _FakeUserEntity_0(
                this,
                Invocation.method(#login, [], {
                  #email: email,
                  #password: password,
                }),
              ),
            ),
          )
          as _i4.Future<_i2.UserEntity>);

  @override
  _i4.Future<void> logout() =>
      (super.noSuchMethod(
            Invocation.method(#logout, []),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<_i2.UserEntity?> getCurrentUser() =>
      (super.noSuchMethod(
            Invocation.method(#getCurrentUser, []),
            returnValue: _i4.Future<_i2.UserEntity?>.value(),
          )
          as _i4.Future<_i2.UserEntity?>);

  @override
  _i4.Future<void> resetPassword({required String? email}) =>
      (super.noSuchMethod(
            Invocation.method(#resetPassword, [], {#email: email}),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> updatePassword({required String? newPassword}) =>
      (super.noSuchMethod(
            Invocation.method(#updatePassword, [], {#newPassword: newPassword}),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);
}
